name: 'Common Actions'
description: 'Reusable steps for MT103 workflows'

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        
    - name: Install dependencies
      run: npm install
      shell: bash
      
    - name: Setup error logging
      run: |
        mkdir -p logs
        touch logs/workflow.log
      shell: bash
        
    - name: Build project
      run: npm run build || (echo "Build failed" >> logs/workflow.log && exit 1)
      shell: bash
