name: Azure Preview Deploy

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

env:
  AZURE_WEBAPP_NAME: mt103-preview
  AZURE_RG_NAME: mt103-preview-rg
  AZURE_LOCATION: westeurope

jobs:
  preview:
    runs-on: ubuntu-latest
    environment: preview
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Build Application
        run: |
          npm ci
          npm run build
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: .
